/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hugojuarez.flightlink;

import com.hugojuarez.flightlink.communication.SerialManager;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import java.io.IOException;

public class Main extends Application {
    private static Scene scene;

    @Override
    public void start(Stage stage) throws IOException {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/views/selection-view.fxml"));
        scene = new Scene(loader.load());
        stage.setScene(scene);
        stage.setTitle("Hello World");
        stage.show();
        stage.centerOnScreen();
    }

    @Override
    public void stop() throws Exception {
        super.stop();
        SerialManager.getInstance().disconnect();
    }

    public static void changeMainView() throws IOException {
        FXMLLoader loader = new FXMLLoader(Main.class.getResource("/views/main-view.fxml"));
        scene.setRoot(loader.load());
    }

    public static void main(String[] args) {
        launch(args);
    }
}
