/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hugojuarez.flightlink;

import org.junit.jupiter.api.Test;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest .getGreeting(), "app should have a greeting");
    }
}
